In [43]:
#Question 1
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype = 'uint16')
print("Shape:  ", np.shape(a))
print("Dimesions:  ", np.ndim(a))
print("Size of an Element:  ", a.itemsize)

Shape:   (4, 2)
Dimesions:   2
Size of an Element:   2


In [44]:
#Question 2
a = np.arange(100, 200, 10)
a.shape = (5, 2) 
print(a)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [32]:
#Question 3
a = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print("Original Array\n", a)
b = a[: , 2]
print("New Array\n", b)

Original Array
 [[11 22 33]
 [44 55 66]
 [77 88 99]]
New Array
 [33 66 99]


In [33]:
#Question 4
a = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print("Original Array\n", a)
b = a[:: 2, 1 :: 2]
print("New Array\n", b)

Original Array
 [[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
New Array
 [[ 6 12]
 [30 36]
 [54 60]]


In [39]:
#Question 5
a1 = np.array([[5, 6, 9], [21 ,18, 27]])
a2 = np.array([[15 ,33, 24], [4 ,7, 1]])
for i in range(2):
    for j in range(3):
        a1[i][j] += a2[i][j]
print("Array after addition\n", a1)
for i in range(2):
    for j in range(3):
        a1[i][j] *= a1[i][j]
print("Array after squaring\n", a1)

Array after addition
 [[20 39 33]
 [25 25 28]]
Array after squaring
 [[ 400 1521 1089]
 [ 625  625  784]]


In [53]:
#Ouestion 7
a = np.array([[34,43,73],[82,22,12],[53,94,66]], dtype = 'i8')
print("Original Array\n", a)
a.view('i8,i8,i8').sort(order=['f1'], axis = 0)
print("Array after sorting by 2nd Column\n", a)
np.flip(a, 0)
np.flip(a, 1)
#Needs Fixing
a.view('i8,i8,i8').sort(order=['f1'], axis = 0)
print("Array after sorting by 2nd Row\n", a)

Original Array
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after sorting by 2nd Column
 [[82 22 12]
 [34 43 73]
 [53 94 66]]
Array after sorting by 2nd Row
 [[82 22 12]
 [34 43 73]
 [53 94 66]]


In [54]:
#Pandas

In [1]:
#Question 6
import pandas as pd
a = pd.read_csv('assignment-1-dataset.csv')
a = a[['company', 'price']] [a.price == a['price'].max()]
print(a)

          company    price
35  mercedes-benz  45400.0


In [ ]:
#Question 7


In [ ]:
#Question 8

In [2]:
#Question 9
a = pd.read_csv('assignment-1-dataset.csv')
b = a.sort_values(by=["price"])
print(b)

    index        company body-style  wheel-base  length engine-type  \
13     16      chevrolet  hatchback        88.4   141.1           l   
27     36          mazda  hatchback        93.1   159.1         ohc   
48     66         toyota  hatchback        95.7   158.7         ohc   
36     49     mitsubishi  hatchback        93.7   157.3         ohc   
28     37          mazda  hatchback        93.1   159.1         ohc   
..    ...            ...        ...         ...     ...         ...   
11     14            bmw      sedan       103.5   193.8         ohc   
35     47  mercedes-benz    hardtop       112.0   199.2        ohcv   
22     31          isuzu      sedan        94.5   155.9         ohc   
23     32          isuzu      sedan        94.5   155.9         ohc   
47     63        porsche  hatchback        98.4   175.7       dohcv   

   num-of-cylinders  horsepower  average-mileage    price  
13            three          48               47   5151.0  
27             four        

In [ ]:
#Question 10